#!/usr/bin/env bash
# This script configures a new Ubuntu machine 
# Installs nginx server and configured to listen at port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
