#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2
# Displays I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
