#!/usr/bin/env bash
# This script displays The content of the current directory In a list 
# format Where only the part of the name after the first dash is displayed

list_dir=$(ls)
for i in $list_dir; do
	echo "$i" | cut -d '-' -f2
done
